{
  "formatVersion": "1.1",
  "component": {
    "group": "net.akkynaa",
    "module": "slotlib",
    "version": "21.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "slotlib-21.1.0.jar",
          "url": "slotlib-21.1.0.jar",
          "size": 58183,
          "sha512": "164de741b4fcf3d79f1efdd2505389d6c099c4b8d3ff3e56953b08a40362d3f06e8553907e653c8525df8f910107dd9aaa372077e8027f86bd42fdbb03fa3c94",
          "sha256": "c27f45b03ae24c7b48ff329efacd52fa3e41b30f5f23db2f140adc43c2da2d4b",
          "sha1": "dd22c5bd935abbfd72ce4305c682ba7ce4a1d998",
          "md5": "7b3e567c5f5f3d600f3bc9b2c95df647"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slotlib-21.1.0.jar",
          "url": "slotlib-21.1.0.jar",
          "size": 58183,
          "sha512": "164de741b4fcf3d79f1efdd2505389d6c099c4b8d3ff3e56953b08a40362d3f06e8553907e653c8525df8f910107dd9aaa372077e8027f86bd42fdbb03fa3c94",
          "sha256": "c27f45b03ae24c7b48ff329efacd52fa3e41b30f5f23db2f140adc43c2da2d4b",
          "sha1": "dd22c5bd935abbfd72ce4305c682ba7ce4a1d998",
          "md5": "7b3e567c5f5f3d600f3bc9b2c95df647"
        }
      ]
    }
  ]
}
