{
  "formatVersion": "1.1",
  "component": {
    "group": "net.akkynaa",
    "module": "slotlib",
    "version": "neoforge-21.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "slotlib-neoforge-21.1.0.jar",
          "url": "slotlib-neoforge-21.1.0.jar",
          "size": 60775,
          "sha512": "4666711182c4d46528c48e01330914a3baa3b5a77bf5f09e0389d030a01a1c0ecdd930691df800a610215d292b59961b83c8bfaddd95a4c37aa64eea81633e57",
          "sha256": "7256134ad95dbd5203699b96893fa1a5f97260ac57c3f4197c5691ef33eef08d",
          "sha1": "2635b64da7c987c8878370e53545b93a1c5f63af",
          "md5": "764676eca0120b6645d64d3ca0488721"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slotlib-neoforge-21.1.0.jar",
          "url": "slotlib-neoforge-21.1.0.jar",
          "size": 60775,
          "sha512": "4666711182c4d46528c48e01330914a3baa3b5a77bf5f09e0389d030a01a1c0ecdd930691df800a610215d292b59961b83c8bfaddd95a4c37aa64eea81633e57",
          "sha256": "7256134ad95dbd5203699b96893fa1a5f97260ac57c3f4197c5691ef33eef08d",
          "sha1": "2635b64da7c987c8878370e53545b93a1c5f63af",
          "md5": "764676eca0120b6645d64d3ca0488721"
        }
      ]
    }
  ]
}
