{
  "formatVersion": "1.1",
  "component": {
    "group": "net.akkynaa",
    "module": "slotlib",
    "version": "neoforge-21.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "slotlib-neoforge-21.1.0.jar",
          "url": "slotlib-neoforge-21.1.0.jar",
          "size": 60867,
          "sha512": "bba2fa2ec364b1b28ef7e238f307992d96c28de379e306532b13a2218be65ea749d29e489a428eb64df4952cee312806a85eae672b83ed52d9fd9c54ed9387e4",
          "sha256": "cba8620a9fd1d0a57fd4f89a7a2c1a944b5a5ff2662b02d414c8b006320d209d",
          "sha1": "6e30da7f8d848e1814614fb1c538fc2625b51ab6",
          "md5": "aaefdfb145b91f1c861bb1ed4c54ab89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slotlib-neoforge-21.1.0.jar",
          "url": "slotlib-neoforge-21.1.0.jar",
          "size": 60867,
          "sha512": "bba2fa2ec364b1b28ef7e238f307992d96c28de379e306532b13a2218be65ea749d29e489a428eb64df4952cee312806a85eae672b83ed52d9fd9c54ed9387e4",
          "sha256": "cba8620a9fd1d0a57fd4f89a7a2c1a944b5a5ff2662b02d414c8b006320d209d",
          "sha1": "6e30da7f8d848e1814614fb1c538fc2625b51ab6",
          "md5": "aaefdfb145b91f1c861bb1ed4c54ab89"
        }
      ]
    }
  ]
}
