{
  "formatVersion": "1.1",
  "component": {
    "group": "net.akkynaa",
    "module": "slotlib",
    "version": "neoforge-21.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "slotlib-neoforge-21.8.0.jar",
          "url": "slotlib-neoforge-21.8.0.jar",
          "size": 56556,
          "sha512": "5fcc7e3e867102aea8e0b17d0e5dec79fa0f466b92bf736e20a0bcf9e1db3001a8d3e6dd3162ff12cd966abd9ea9a4b602cb4b8ce34c5f881209bf01eae1e64c",
          "sha256": "868de63b2c7a1573f58cd7dffc1cb4b5f405bfb35f99ace15df1338dd0bb09a6",
          "sha1": "152017073fc24b43dffdb22616048d6bce922efe",
          "md5": "ab27b0988f6f4cd00b12d9dbaedcef9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.8.49"
          }
        }
      ],
      "files": [
        {
          "name": "slotlib-neoforge-21.8.0.jar",
          "url": "slotlib-neoforge-21.8.0.jar",
          "size": 56556,
          "sha512": "5fcc7e3e867102aea8e0b17d0e5dec79fa0f466b92bf736e20a0bcf9e1db3001a8d3e6dd3162ff12cd966abd9ea9a4b602cb4b8ce34c5f881209bf01eae1e64c",
          "sha256": "868de63b2c7a1573f58cd7dffc1cb4b5f405bfb35f99ace15df1338dd0bb09a6",
          "sha1": "152017073fc24b43dffdb22616048d6bce922efe",
          "md5": "ab27b0988f6f4cd00b12d9dbaedcef9d"
        }
      ]
    }
  ]
}
