{
  "formatVersion": "1.1",
  "component": {
    "group": "net.akkynaa",
    "module": "slotlib",
    "version": "neoforge-21.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "slotlib-neoforge-21.5.0.jar",
          "url": "slotlib-neoforge-21.5.0.jar",
          "size": 58135,
          "sha512": "5bba4ad43bd880f48f5b224c76c148fe2b74178217c3e26c6302467490d1e01857819730ea72f328b2c26c04a2ec0b01555375db70855596f8f8ac117cb15e6b",
          "sha256": "fed3952d731c36f8b89a0217a6e2aae4dc32f6ecaa7ca3872bea1b903dc56985",
          "sha1": "fc9ca7d8d264f90f2d16f17376d9293aa87beee1",
          "md5": "241ddb30ba0101c7748bcc3a987d133b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.5.95"
          }
        }
      ],
      "files": [
        {
          "name": "slotlib-neoforge-21.5.0.jar",
          "url": "slotlib-neoforge-21.5.0.jar",
          "size": 58135,
          "sha512": "5bba4ad43bd880f48f5b224c76c148fe2b74178217c3e26c6302467490d1e01857819730ea72f328b2c26c04a2ec0b01555375db70855596f8f8ac117cb15e6b",
          "sha256": "fed3952d731c36f8b89a0217a6e2aae4dc32f6ecaa7ca3872bea1b903dc56985",
          "sha1": "fc9ca7d8d264f90f2d16f17376d9293aa87beee1",
          "md5": "241ddb30ba0101c7748bcc3a987d133b"
        }
      ]
    }
  ]
}
