{
  "formatVersion": "1.1",
  "component": {
    "group": "net.akkynaa",
    "module": "slotlib",
    "version": "neoforge-21.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "slotlib-neoforge-21.11.0.jar",
          "url": "slotlib-neoforge-21.11.0.jar",
          "size": 54875,
          "sha512": "026b13043a2e856b197d6ffe9ed3cda615934cf21f2954981bfe998f8f21f33b84d0c7ddaf25733c301cef25d796c5d0e39a3716043adce7b1331038be18977d",
          "sha256": "2c7737b436d7e5305350be8df6c6495d5973164841d4be43198223c336e9411b",
          "sha1": "6f4b2847ba0962bd49724377cad911d29505ecb3",
          "md5": "f12449b8ffcd109f3bb860f1e99fc773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.11.38-beta"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "14.0.0+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "slotlib-neoforge-21.11.0.jar",
          "url": "slotlib-neoforge-21.11.0.jar",
          "size": 54875,
          "sha512": "026b13043a2e856b197d6ffe9ed3cda615934cf21f2954981bfe998f8f21f33b84d0c7ddaf25733c301cef25d796c5d0e39a3716043adce7b1331038be18977d",
          "sha256": "2c7737b436d7e5305350be8df6c6495d5973164841d4be43198223c336e9411b",
          "sha1": "6f4b2847ba0962bd49724377cad911d29505ecb3",
          "md5": "f12449b8ffcd109f3bb860f1e99fc773"
        }
      ]
    }
  ]
}
