{
  "formatVersion": "1.1",
  "component": {
    "group": "net.akkynaa",
    "module": "slotlib",
    "version": "neoforge-21.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "slotlib-neoforge-21.11.0.jar",
          "url": "slotlib-neoforge-21.11.0.jar",
          "size": 54740,
          "sha512": "b3b65f8f84a6558cb6e2e8c671bb8d1de4497b03d3fcb7a8db2bd117426c1e6fda2fceb9e9316f0335ab93a002afbc173d4474d16d725c878e25e868ce3f4777",
          "sha256": "b627ec312d5332682fed70c45e93324329f9218ae85832de33e88f56ee4efb1b",
          "sha1": "f6f234317274f71a9f8202238f2d1430e2a8c53a",
          "md5": "cfc548be307518a9e103402dbcceaa7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoforge",
          "version": {
            "requires": "21.11.38-beta"
          }
        },
        {
          "group": "top.theillusivec4.curios",
          "module": "curios-neoforge",
          "version": {
            "requires": "14.0.0+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "slotlib-neoforge-21.11.0.jar",
          "url": "slotlib-neoforge-21.11.0.jar",
          "size": 54740,
          "sha512": "b3b65f8f84a6558cb6e2e8c671bb8d1de4497b03d3fcb7a8db2bd117426c1e6fda2fceb9e9316f0335ab93a002afbc173d4474d16d725c878e25e868ce3f4777",
          "sha256": "b627ec312d5332682fed70c45e93324329f9218ae85832de33e88f56ee4efb1b",
          "sha1": "f6f234317274f71a9f8202238f2d1430e2a8c53a",
          "md5": "cfc548be307518a9e103402dbcceaa7f"
        }
      ]
    }
  ]
}
